# Generated by Django 5.0.2 on 2024-03-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название_курса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание_курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='превью_курса')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название_урока')),
                ('description', models.TextField(verbose_name='описание_урока')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/lessons/', verbose_name='превью_урока')),
                ('link', models.URLField(blank=True, null=True, verbose_name='ссылка_на_видео')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
